// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcEfTurkiye.Data;

#nullable disable

namespace MvcEfTurkiye.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcEfTurkiye.Data.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SehirAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sehirler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SehirAd = "Adana"
                        },
                        new
                        {
                            Id = 2,
                            SehirAd = "Adıyaman"
                        },
                        new
                        {
                            Id = 3,
                            SehirAd = "Afyonkarahisar"
                        },
                        new
                        {
                            Id = 4,
                            SehirAd = "Ağrı"
                        },
                        new
                        {
                            Id = 5,
                            SehirAd = "Amasya"
                        },
                        new
                        {
                            Id = 6,
                            SehirAd = "Ankara"
                        },
                        new
                        {
                            Id = 7,
                            SehirAd = "Antalya"
                        },
                        new
                        {
                            Id = 8,
                            SehirAd = "Artvin"
                        },
                        new
                        {
                            Id = 9,
                            SehirAd = "Aydın"
                        },
                        new
                        {
                            Id = 10,
                            SehirAd = "Balıkesir"
                        },
                        new
                        {
                            Id = 11,
                            SehirAd = "Bilecik"
                        },
                        new
                        {
                            Id = 12,
                            SehirAd = "Bingöl"
                        },
                        new
                        {
                            Id = 13,
                            SehirAd = "Bitlis"
                        },
                        new
                        {
                            Id = 14,
                            SehirAd = "Bolu"
                        },
                        new
                        {
                            Id = 15,
                            SehirAd = "Burdur"
                        },
                        new
                        {
                            Id = 16,
                            SehirAd = "Bursa"
                        },
                        new
                        {
                            Id = 17,
                            SehirAd = "Çanakkale"
                        },
                        new
                        {
                            Id = 18,
                            SehirAd = "Çankırı"
                        },
                        new
                        {
                            Id = 19,
                            SehirAd = "Çorum"
                        },
                        new
                        {
                            Id = 20,
                            SehirAd = "Denizli"
                        },
                        new
                        {
                            Id = 21,
                            SehirAd = "Diyarbakır"
                        },
                        new
                        {
                            Id = 22,
                            SehirAd = "Edirne"
                        },
                        new
                        {
                            Id = 23,
                            SehirAd = "Elazığ"
                        },
                        new
                        {
                            Id = 24,
                            SehirAd = "Erzincan"
                        },
                        new
                        {
                            Id = 25,
                            SehirAd = "Erzurum"
                        },
                        new
                        {
                            Id = 26,
                            SehirAd = "Eskişehir"
                        },
                        new
                        {
                            Id = 27,
                            SehirAd = "Gaziantep"
                        },
                        new
                        {
                            Id = 28,
                            SehirAd = "Giresun"
                        },
                        new
                        {
                            Id = 29,
                            SehirAd = "Gümüşhane"
                        },
                        new
                        {
                            Id = 30,
                            SehirAd = "Hakkari"
                        },
                        new
                        {
                            Id = 31,
                            SehirAd = "Hatay"
                        },
                        new
                        {
                            Id = 32,
                            SehirAd = "Isparta"
                        },
                        new
                        {
                            Id = 33,
                            SehirAd = "Mersin"
                        },
                        new
                        {
                            Id = 34,
                            SehirAd = "İstanbul"
                        },
                        new
                        {
                            Id = 35,
                            SehirAd = "İzmir"
                        },
                        new
                        {
                            Id = 36,
                            SehirAd = "Kars"
                        },
                        new
                        {
                            Id = 37,
                            SehirAd = "Kastamonu"
                        },
                        new
                        {
                            Id = 38,
                            SehirAd = "Kayseri"
                        },
                        new
                        {
                            Id = 39,
                            SehirAd = "Kırklareli"
                        },
                        new
                        {
                            Id = 40,
                            SehirAd = "Kırşehir"
                        },
                        new
                        {
                            Id = 41,
                            SehirAd = "Kocaeli"
                        },
                        new
                        {
                            Id = 42,
                            SehirAd = "Konya"
                        },
                        new
                        {
                            Id = 43,
                            SehirAd = "Kütahya"
                        },
                        new
                        {
                            Id = 44,
                            SehirAd = "Malatya"
                        },
                        new
                        {
                            Id = 45,
                            SehirAd = "Manisa"
                        },
                        new
                        {
                            Id = 46,
                            SehirAd = "Kahramanmaraş"
                        },
                        new
                        {
                            Id = 47,
                            SehirAd = "Mardin"
                        },
                        new
                        {
                            Id = 48,
                            SehirAd = "Muğla"
                        },
                        new
                        {
                            Id = 49,
                            SehirAd = "Muş"
                        },
                        new
                        {
                            Id = 50,
                            SehirAd = "Nevşehir"
                        },
                        new
                        {
                            Id = 51,
                            SehirAd = "Niğde"
                        },
                        new
                        {
                            Id = 52,
                            SehirAd = "Ordu"
                        },
                        new
                        {
                            Id = 53,
                            SehirAd = "Rize"
                        },
                        new
                        {
                            Id = 54,
                            SehirAd = "Sakarya"
                        },
                        new
                        {
                            Id = 55,
                            SehirAd = "Samsun"
                        },
                        new
                        {
                            Id = 56,
                            SehirAd = "Siirt"
                        },
                        new
                        {
                            Id = 57,
                            SehirAd = "Sinop"
                        },
                        new
                        {
                            Id = 58,
                            SehirAd = "Sivas"
                        },
                        new
                        {
                            Id = 59,
                            SehirAd = "Tekirdağ"
                        },
                        new
                        {
                            Id = 60,
                            SehirAd = "Tokat"
                        },
                        new
                        {
                            Id = 61,
                            SehirAd = "Trabzon"
                        },
                        new
                        {
                            Id = 62,
                            SehirAd = "Tunceli"
                        },
                        new
                        {
                            Id = 63,
                            SehirAd = "Şanlıurfa"
                        },
                        new
                        {
                            Id = 64,
                            SehirAd = "Uşak"
                        },
                        new
                        {
                            Id = 65,
                            SehirAd = "Van"
                        },
                        new
                        {
                            Id = 66,
                            SehirAd = "Yozgat"
                        },
                        new
                        {
                            Id = 67,
                            SehirAd = "Zonguldak"
                        },
                        new
                        {
                            Id = 68,
                            SehirAd = "Aksaray"
                        },
                        new
                        {
                            Id = 69,
                            SehirAd = "Bayburt"
                        },
                        new
                        {
                            Id = 70,
                            SehirAd = "Karaman"
                        },
                        new
                        {
                            Id = 71,
                            SehirAd = "Kırıkkale"
                        },
                        new
                        {
                            Id = 72,
                            SehirAd = "Batman"
                        },
                        new
                        {
                            Id = 73,
                            SehirAd = "Şırnak"
                        },
                        new
                        {
                            Id = 74,
                            SehirAd = "Bartın"
                        },
                        new
                        {
                            Id = 75,
                            SehirAd = "Ardahan"
                        },
                        new
                        {
                            Id = 76,
                            SehirAd = "Iğdır"
                        },
                        new
                        {
                            Id = 77,
                            SehirAd = "Yalova"
                        },
                        new
                        {
                            Id = 78,
                            SehirAd = "Karabük"
                        },
                        new
                        {
                            Id = 79,
                            SehirAd = "Kilis"
                        },
                        new
                        {
                            Id = 80,
                            SehirAd = "Osmaniye"
                        },
                        new
                        {
                            Id = 81,
                            SehirAd = "Düzce"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
